<?php

/**
 * @file
 * Contains hooks for Instagram module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function instag_entity_extra_field_info() {
  $extra = [];

  $extra['instagram_post']['instagram_post']['display']['link'] = [
    'label' => t('Link'),
    'description' => t('Link to Instagram post.'),
    'weight' => 100,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function instag_instagram_post_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('link')) {
    $link = $entity->getLink();
    $build['link'] = [
      '#type' => 'markup',
      '#markup' => sprintf('<a href="%s" rel="noopener">%s</a>', $link, $link),
    ];
  }
}
